# Generated by Django 4.1.1 on 2022-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_acquisition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='founded_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='funding_rounds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='milestones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='relationships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='total_funding_usd',
            field=models.IntegerField(),
        ),
    ]
